import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionNavbarWrapper from "./components/Navbar";
import { getUserFromSession } from './lib/auth'
import { ThemeProvider } from "@/context/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getUserFromSession();
  const isLoggedIn = !!user;
  return (
    <html lang="en">
<ThemeProvider> 
     <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionNavbarWrapper  isLoggedIn={isLoggedIn}/>
        {children}
      </body>
  </ThemeProvider>  
    </html>
  );
}
