import type { Metadata } from "next";
import { Inter } from "next/font/google"; 
import localFont from "next/font/local";
import "./globals.css";
import { getUserFromSession } from '../../lib/auth'
import { ThemeProvider } from "@/context/ThemeProvider";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: [
    {
      path: '../fonts/Geist-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/Geist-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/Geist-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: [
    {
      path: '../fonts/GeistMono-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/GeistMono-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: "--font-geist-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

const user = await getUserFromSession();
const isLoggedIn = !!user?.userId;
console.log("User:", user?.userId);
console.log("Is logged in:", isLoggedIn);
  return (
    <html lang="en">
<ThemeProvider> 
     <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar  isLoggedIn={isLoggedIn}/>
        {children}
      </body>
  </ThemeProvider>  
    </html>
  );
}
